### ISSUE TITLE
+window-count+ type declamation is incompatible with its value

### ISSUE THREAD

**Issue by Yehouda** [y2q-actionman/cl-scsu#1]
in src/constant.lisp, **+window-count+**  is defined as a constant with value 8, and then declaimed as type **window-index**, which is **(integer 0 7)**. That is incompatible. 

Lispworks actually gives an error in this case.

**Comment by y2q-actionman** [comment]
I confirmed. The `(integer 0 7)` for `+window-count+` is incorrect.
In commit ba60250, I changed its type and some other constants.

Thank you.
