### ISSUE TITLE
SCSU-ERROR uses a bits from simple-condition but does inherit from it.

### ISSUE THREAD

**Issue by Yehouda** [y2q-actionman/cl-scsu#2]
The condiiton **scsu-error** uses the reader **simple-conditon-format-control** in the **:report** lambda, and calls to **error** with **scsu-error** pass **:format-control** and **:format-arguments**. These are normally inherited from **simple-condition**, but **scsu-error** does not inherit from **simple-condition**.

**scsu-error** needs to inherit from **simple-error** (which inherits from **simple-condition**),  instead of **error**.

**Comment by y2q-actionman** [comment]
Ok, I changed to use `simple-error` for `scsu-error`.
